version: "3.8"
services:
  unleash:
    build: ./image
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://admin:password@unleash-db/unleash
      AUTH_HOST: https://iam.cloud-iam.com
      AUTH_REALM: unleash
      AUTH_CLIENT_ID: unleash
    depends_on:
      - unleash-db
    command: npm run start

  unleash-db:
    expose:
      - "5432"
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
    driver: local
